// Authoring fill for empty CSV cells. Distinct voices — never copy Mentor into
// Best Friend / Mother / Roaster. Runtime still falls back to that guide's own
// page default if a step cell is blank.

export const FILL = {
  'userInfo::default': {
    bestFriend: "Just the basics — name, role, the people you actually lead. We'll get to the messy stuff together.",
    mother: "Start with what's true and ordinary: your name, your work, your people. You don't have to prove anything on this page.",
    roaster: "Name, job, team. Don't audition. Save the performance for people who didn't ask.",
  },
  'guideSelect::default': {
    bestFriend: "Pick the voice you'd actually want in your ear for a year. You can swap later — first gut is usually right.",
    mother: "Choose the companion you can stand hearing when you're tired. Comfort isn't always kindness, but you should feel accompanied.",
    roaster: "Don't pick the one that flatters you. Pick the one that would call you on your nonsense.",
  },
  'intake::default': {
    bestFriend: "Answer like we're talking after work, not like you're writing a bio. I already like you. I want the real version.",
    mother: "Tell the truth about how you lead on a normal Tuesday. Impressive is not useful. Honest is.",
    roaster: "If you're crafting the answer, you're wasting both our time. Pick the one that makes you wince a little.",
  },
  'intake::behaviors-intro': {
    mentor: "These questions are about how you actually move — not the leader you present in a meeting.",
    catalyst: "Twelve questions. Keep a pace. First impulse, then we go.",
    challenger: "Don't rehearse. The useful answers are the ones you already know and avoid saying.",
    bestFriend: "Okay — habits next. No speech. Just how you show up when nobody's writing it down.",
    mother: "We'll go through how you usually lead. Sit up, breathe, and don't dress it for company.",
    roaster: "Behavior time. If you start sounding like a LinkedIn post, I'm throwing it out.",
  },
  'intake::q-resourcePick': {
    mentor: "When it's tight, something gives. Name what you actually move first — not what you wish you protected.",
    catalyst: "Gut pick. Time, money, scope, or the story you tell people. Go.",
    challenger: "Don't pick the virtuous one. Pick the one you actually sacrifice.",
    bestFriend: "Be honest — when it gets crunchy, what do you move first? I won't flinch.",
    mother: "Scarcity shows priorities. What do you usually let slip so the work can continue?",
    roaster: "Ah yes, the noble resource you never actually cut. Try again.",
  },
  'intake::q-projectApproach': {
    mentor: "First move on a hard project says a lot. Choose the one you'd actually take, not the one that photographs well.",
    catalyst: "Clock's running. What's your opening move — plan, dive, huddle, or clarify?",
    challenger: "Your first move is a tell. Don't pick the one you describe in interviews.",
    bestFriend: "Complex project, tight clock — what do you actually do first? No TED Talk.",
    mother: "When the work is heavy, how do you gather yourself and the team? The real first step.",
    roaster: "Don't tell me you 'align stakeholders.' What do you do in the first hour?",
  },
  'intake::q-energyDrains': {
    mentor: "Name the three that drain you. That's data, not complaint.",
    catalyst: "Three drains. Fast. We'll use them later.",
    challenger: "Don't pick the ones that sound professional. Pick the ones that make you short with people.",
    bestFriend: "Which three make you want to hide in the car? That's the list.",
    mother: "What wears you thin? Name three. You don't have to justify them.",
    roaster: "The polite drains aren't the real ones. Pick the ones that make you snippy.",
  },
  'intake::q-crisisResponse': {
    mentor: "Rank how you actually move when it breaks — composure, huddle, clarity, delegate, or jump in.",
    catalyst: "Crisis rank. Don't overthink the order. Your body already knows.",
    challenger: "Rank the truth, not the training. Who do you become when it hits?",
    bestFriend: "When it blows up — be real about the order you actually run.",
    mother: "In a scare, how do you protect the work and the people? Rank what you really do.",
    roaster: "Crisis cosplay is easy. Rank the version of you that shows up at 4:47 p.m.",
  },
  'intake::q-pushbackFeeling': {
    mentor: "When you're challenged, the feeling is information. Name it without cleaning it up.",
    catalyst: "Pushback hits — what's the first feeling? Don't editorialize.",
    challenger: "If you say 'curious,' I'm not buying it. What's actually in your chest?",
    bestFriend: "When someone pushes back, what's the honest feeling? I can hold it.",
    mother: "Being challenged can sting. Name the feeling before you manage it.",
    roaster: "Don't intellectualize. When they push, what flares first?",
  },
  'intake::q-roleModelTrait': {
    mentor: "The leader you admire is a clue. Name the trait, not the résumé.",
    catalyst: "Who do you secretly want to lead like? One trait. Go.",
    challenger: "Don't pick a saint. Pick the trait you actually envy.",
    bestFriend: "Who do you look at and think 'that'? What's the trait, not the title.",
    mother: "Who taught you, even from a distance? What did they do that you still carry?",
    roaster: "Your role model isn't a brand. What do they do that you still haven't?",
  },
  'intake::q-warningLabel': {
    mentor: "Your warning label is a gift if you say it plainly.",
    catalyst: "Warning label. Short. The one your team would write.",
    challenger: "Write the label your team already whispers. That's the one.",
    bestFriend: "If I had to warn a friend about working with you — what's the kind version of the true one?",
    mother: "Every leader has a caution. Say yours without shame. We'll work with it.",
    roaster: "Handle with care: you. What's on the sticker?",
  },
  'intake::q-leaderFuel': {
    mentor: "What actually fills the tank? Not what should.",
    catalyst: "Fuel. The thing that makes you want Monday.",
    challenger: "Don't pick 'the team succeeding' if the real fuel is control. Be precise.",
    bestFriend: "What actually lights you up in the work? I'll take the uncool answer.",
    mother: "What restores you as a leader? Name it so we can protect it.",
    roaster: "The fuel that sounds noble and the fuel that's real — pick the second.",
  },
  'intake::q-proudMoment': {
    mentor: "A real accomplishment — what did you actually do, and what did the team feel?",
    catalyst: "Highlight reel. One moment. Keep it specific.",
    challenger: "If the story needs you as hero, shrink it until the team is visible.",
    bestFriend: "Tell me a moment you're proud of without making it a legend.",
    mother: "A time the work went well. Who was helped, and what did you do?",
    roaster: "Skip the keynote version. What actually happened?",
  },
  'intake::q-behaviorDichotomies': {
    mentor: "The sliders are a balance line. Sit where you really live, not the middle to look mature.",
    catalyst: "Slide honestly. Middle is a hide if you're using it that way.",
    challenger: "If every slider is a 5, you're lying. Commit to a side.",
    bestFriend: "These sliders aren't a personality quiz. Park them where you actually operate.",
    mother: "There's no perfect middle. Place yourself where your people would place you.",
    roaster: "Center-seeking isn't wisdom. It's camouflage. Move the sliders.",
  },
  'intake::q-visibilityComfort': {
    mentor: "High visibility — do you step in, or do you manage the feeling first?",
    catalyst: "Spotlight. Comfortable, or performing comfort?",
    challenger: "If you hate the spotlight, say so. Hiding it doesn't make you humble.",
    bestFriend: "When all eyes are on you, what's true — ease, freeze, or a bit of both?",
    mother: "Being seen can be a lot. How do you actually hold it?",
    roaster: "Visibility: do you hunt it, tolerate it, or pretend you don't care?",
  },
  'intake::q-decisionPace': {
    mentor: "When something goes wrong, what's your real loop — speed, study, or blame dressed as learning?",
    catalyst: "Wrong turn. Do you iterate or freeze? First true move.",
    challenger: "Don't tell me you 'learn fast' if you actually stew. Pick the real pace.",
    bestFriend: "When it breaks, how fast do you actually move versus how fast you talk about moving?",
    mother: "A miss happened. How do you come back to the people and the work?",
    roaster: "The lesson loop you advertise vs the one you run. Rank the second.",
  },
  'intake::q-teamPerception': {
    mentor: "Someone's missing it. What do you actually do — name it, wait, absorb, or over-help?",
    catalyst: "Missed expectations. Your real move, not HR's.",
    challenger: "If you 'give it time' forever, that's avoidance. What do you do in week two?",
    bestFriend: "When a person isn't landing it, how do you actually handle them — not the handbook version.",
    mother: "Someone's struggling. How do you tell the truth without abandoning them?",
    roaster: "Underperformance: coach, ghost, or do it yourself? Be ugly-honest.",
  },
  'intake::reflection': {
    mentor: "Pause. This is a mirror, not a recap of the five questions. Sit with what surprised you.",
    catalyst: "Quick sit. If something snagged, name it. Then we move into mindset.",
    challenger: "Don't skip the pause because you're 'fine.' Fine is a fog.",
    bestFriend: "Hey — before the next block. Anything from those questions still sitting in your chest?",
    mother: "Catch your breath. You don't have to solve it. Just notice what landed.",
    roaster: "Reflection moment. Don't perform insight. One true thing you noticed is enough.",
  },
  'intake::mindset-intro': {
    mentor: "Next are scales about how you see people and work. Same rule: how you actually think, not the creed.",
    catalyst: "Ten scales. Keep moving. Honest beats careful.",
    challenger: "These look like values questions. They're habits of mind. Don't sermonize.",
    bestFriend: "Mindset next — how you actually see folks, not the poster on the wall.",
    mother: "A short stretch of how you see the world of work. Gentle, and true.",
    roaster: "Insights block. If you answer like a keynote, I'm going to know.",
  },
  'intake::societal-1': {
    mentor: "First scale. Don't average yourself into safety.",
    catalyst: "Scale one. First number, then next.",
    challenger: "If you're hovering at 5, ask whether that's honesty or hiding.",
    bestFriend: "First one — pick the number you'd say to me, not to a board.",
    mother: "Start where you really live on this, not where you look balanced.",
    roaster: "Scale one. The middle is not a personality.",
  },
  'intake::societal-2': {
    mentor: "Stay with how you actually operate, not how you teach it.",
    catalyst: "Two. Keep the pace.",
    challenger: "Don't correct toward the 'right' leader. Score the real one.",
    bestFriend: "Still with me. Same honesty as the first.",
    mother: "Another one. No need to be consistent with a story. Be consistent with yourself.",
    roaster: "Two. If you're decorating the number, stop.",
  },
  'intake::societal-3': {
    mentor: "Notice if you're managing the impression. Let the number be plain.",
    catalyst: "Three. Gut.",
    challenger: "The number you hesitate on is probably the true one.",
    bestFriend: "Three. If you're overthinking, that's the tell.",
    mother: "You're allowed to land on an uncomfortable number.",
    roaster: "Three. Stop shopping for the flattering tick.",
  },
  'intake::societal-4': {
    mentor: "Halfway-ish. Still the leader you are, not the syllabus.",
    catalyst: "Four. Don't slow down to look wise.",
    challenger: "If this one stings, good. That's the data.",
    bestFriend: "Four. We can talk about the sting later.",
    mother: "Keep going. Uncomfortable is not the same as wrong.",
    roaster: "Four. If it feels like a trap, that's just honesty arriving.",
  },
  'intake::societal-5': {
    mentor: "Midpoint. Recalibrate to truth, not to the last four answers.",
    catalyst: "Five. Fresh eyes. Don't pattern-match yourself.",
    challenger: "Don't make a streak. Make an accurate mark.",
    bestFriend: "Halfway. You're doing fine. Keep it real.",
    mother: "Rest a second if you need, then place this one truly.",
    roaster: "Five. Streaks are for bowling, not self-report.",
  },
  'intake::societal-6': {
    mentor: "These later ones often show the real tilt. Stay honest.",
    catalyst: "Six. Still moving.",
    challenger: "Fatigue is when the mask slips. Let it.",
    bestFriend: "Six. Tired answers can be the truest. That's okay.",
    mother: "If you're weary, that's alright. Weary and honest still counts.",
    roaster: "Six. The polite answers already had their turn.",
  },
  'intake::societal-7': {
    mentor: "Almost there. Don't rush the last few into a blur.",
    catalyst: "Seven. Same speed, same honesty.",
    challenger: "Rushing is a way to not see it. Slow the click.",
    bestFriend: "Seven. I know these get old. One true number anyway.",
    mother: "A few left. Each one still deserves a real placement.",
    roaster: "Seven. Don't speedrun your personality.",
  },
  'intake::societal-8': {
    mentor: "Two more after this. Stay with the question in front of you.",
    catalyst: "Eight. Finish strong means finish honest.",
    challenger: "If you're answering the set instead of the item, start over on this one.",
    bestFriend: "Eight. This one, not the average of the last seven.",
    mother: "This question is its own. Place it as if it were the only one.",
    roaster: "Eight. Stop answering the quiz. Answer the sentence.",
  },
  'intake::societal-9': {
    mentor: "Nearly done. Last chance to be exact before the close.",
    catalyst: "Nine. One more after.",
    challenger: "Don't coast. Coasting is how you stay unknown to yourself.",
    bestFriend: "Nine. You've been honest — keep that through the last ones.",
    mother: "Almost. Hold your own hand and tell the truth.",
    roaster: "Nine. You can see the finish line. Don't start lying to get there.",
  },
  'intake::societal-10': {
    mentor: "Last scale. Let it be as true as the first.",
    catalyst: "Ten. Then we close this block.",
    challenger: "Last one. If you've been hedging, stop here.",
    bestFriend: "Last scale. Then we get you a breather.",
    mother: "The last of these. Set it down honestly and we'll continue.",
    roaster: "Ten. Don't make it a bow. Make it accurate.",
  },
  'summary::default': {
    bestFriend: "Read it like I wrote you a letter. Notice what hugs and what bruises — both count.",
    mother: "Go slowly. You don't have to agree with every line. You do have to hear it.",
    roaster: "The lines you want to argue with? Start there. That's the assignment.",
  },
  'summary::trailhead': {
    mentor: "Mirror the current signal. Your clearest current-state leadership reflection.",
    catalyst: "This is the now-shot. Don't skip it to get to the 'action' part.",
    challenger: "If this doesn't sting somewhere, you weren't honest in the intake.",
    bestFriend: "This is you, right now. Sit with it before you start fixing the plot.",
    mother: "Here is how you look at the trailhead. Let the current picture land.",
    roaster: "Trailhead: the you that actually showed up, not the brochure.",
  },
  'summary::markers': {
    mentor: "Notice the recurring moments — signals that show up under pressure and momentum.",
    catalyst: "Patterns, not one-offs. Circle what keeps repeating.",
    challenger: "If it happened twice, it's not a fluke. Read the markers.",
    bestFriend: "The repeats — that's your signature, for better and for worse.",
    mother: "What keeps returning in your leadership? Those markers are trying to teach you.",
    roaster: "Markers aren't trivia. They're the bits you keep doing on purpose or by accident.",
  },
  'summary::hazards': {
    mentor: "What may break if left unaddressed. Sit with the risk before you skip past it.",
    catalyst: "Hazards are the 'if we do nothing' slide. Don't rush it.",
    challenger: "These are stay-the-same risks. Pretending they're dramatic makes them easier to ignore.",
    bestFriend: "This part's the warning. I'm with you — still read it.",
    mother: "These are the places you could get hurt, or hurt them, by staying the same.",
    roaster: "Hazards. Not movie villains — the boring ways you keep tripping.",
  },
  'summary::new-trail': {
    mentor: "Choose where to build forward. Focused growth traits create a sharper trajectory.",
    catalyst: "Forward now. We'll pick three traits next — don't collect ten.",
    challenger: "A new trail isn't a rebrand. It's a narrower promise.",
    bestFriend: "Okay — where do we actually walk next? Smaller is kinder here.",
    mother: "The path ahead should fit a real week, not a fantasy quarter.",
    roaster: "New trail. If it needs a slogan, it's too big. Shrink it.",
  },
  'traitSelection::default': {
    bestFriend: "Three traits. Pick the ones that would change life for the people you lead — not your highlight reel.",
    mother: "Choose the three that would help your people most. Vanity traits can wait.",
    roaster: "If you pick the easy three, we both know. Pick the ones you've been dodging.",
  },
  'traitSelection::focus-trait': {
    mentor: "Look closely. Does this one change anything for the people who work with you?",
    catalyst: "Interesting. Would this one actually move a week, or just look good on the list?",
    challenger: "Don't fall in love with the label. Would your team feel this if you grew it?",
    bestFriend: "Hold it up. Would your people actually feel a difference if you worked this?",
    mother: "Is this the work that would ease something for them, or only for your résumé?",
    roaster: "Cute card. Would anyone you lead notice if you got better at this?",
  },
  'traitSelection::selected-1': {
    mentor: "One in. Choose the second because it matters, not because it matches.",
    catalyst: "One down. Keep the energy. Second pick.",
    challenger: "One is a start. Don't pick a rhyming second.",
    bestFriend: "Nice — one. What's the next one your team would vote for?",
    mother: "Good. One chosen. Let the next one be useful, not pretty.",
    roaster: "One. Don't build a theme park. Pick another real problem.",
  },
  'traitSelection::selected-2': {
    mentor: "Two. The third is usually the one you've been circling.",
    catalyst: "Two. The last one is the decision. Make it.",
    challenger: "The third is where people hide. Don't.",
    bestFriend: "Two in. The last one is the brave one. You know which.",
    mother: "Two is enough to feel real. The third should be the needed one.",
    roaster: "Two. If the third is 'strategic presence,' I'm walking out.",
  },
  'traitSelection::selected-3': {
    mentor: "Three. If they feel a little sharp, you probably chose well.",
    catalyst: "Locked. Let's build the campaign before you renegotiate with yourself.",
    challenger: "Three. Live with them. Second-guessing is how you pick softer ones.",
    bestFriend: "That's the set. We can work with these. Let's go make the sentences.",
    mother: "Three is a full hand. We'll treat them as a year's work, not a mood.",
    roaster: "Three. No take-backsies unless they're actually wrong. They're probably not.",
  },
  'campaignIntro::default': {
    bestFriend: "A campaign is a small test, not a personality overhaul. We're running something your team can actually answer.",
    mother: "This isn't a makeover. It's a bounded stretch of work your people can speak to.",
    roaster: "If this 'campaign' needs a launch party, it's too big. Shrink it.",
  },
  'campaignBuilder::default': {
    bestFriend: "Keep the sentences your team could say without rolling their eyes. Cut the rest.",
    mother: "Read each line as if you were them. If it isn't fair, it doesn't belong.",
    roaster: "If you wouldn't want to be rated on it, throw it out.",
  },
  'campaignBuilder::curating': {
    mentor: "Keep what's fair and useful. Remove anything confusing, theatrical, or outside this stretch.",
    catalyst: "Edit fast. Useful stays. Mush goes.",
    challenger: "If a prompt is vague, it's a gift to your ego and a tax on your team. Cut it.",
    bestFriend: "You're curating. Be kind to the people who'll click through these.",
    mother: "Only keep what a decent person could rate in good faith.",
    roaster: "If you have to explain the prompt, it's a bad prompt.",
  },
  'campaignBuilder::ready-to-verify': {
    mentor: "This set looks complete. Next you rate yourself, then a different link goes to the team.",
    catalyst: "Looks shippable. Verify, then self, then invite. In that order.",
    challenger: "Don't stall in editing. If it's fair, move.",
    bestFriend: "This is enough. Let's lock it and do your self-rating next.",
    mother: "Good. We'll look once more, then you go first before anyone else.",
    roaster: "Stop polishing. Verify it and take your own medicine first.",
  },
  'campaignVerify::default': {
    bestFriend: "Last look. Read it like you're the person opening the invite — then you go first, not them.",
    mother: "Check it once more. You rate yourself before anyone else sees this.",
    roaster: "If it feels mushy, rewrite before humans see it. Then you score yourself. Team later.",
  },
  'campaignVerify::about-to-launch': {
    mentor: "Self first. Team link second. Do not mix the URLs.",
    catalyst: "You, then them. Separate link. Separate password.",
    challenger: "If you send them your self link, you deserve the mess. Don't.",
    bestFriend: "You're about to go. Your survey, then their survey. Two different doors.",
    mother: "You go first so the comparison is honest. Then we invite them carefully.",
    roaster: "Launch courage isn't blasting Slack. It's you taking the same test, then sending the other URL.",
  },
  'campaignRun::default': {
    bestFriend: "Score what you actually experience. No protecting, no punishing. Just true.",
    mother: "Answer as a person who works with them, not as a judge or a fan.",
    roaster: "Don't game the scale. Pretend you're rating a colleague you respect and also see clearly.",
  },
  'campaignComplete::default': {
    bestFriend: "That's it. Thank you. Go on with your day — you did the useful thing.",
    mother: "Well done. You can set this down. The leader will see a pattern, not your name.",
    roaster: "Done. You were honest, I hope. That's the whole job.",
  },
  'dashboardToday::default': {
    bestFriend: "Hey. Start where you actually are this week — not where the plan said you'd be.",
    mother: "Come in. Look at the season name. It is allowed to be true.",
    roaster: "Before you click around: which tile are you avoiding? That's the assignment.",
  },
  'dashboardToday::season': {
    mentor: "The season name is honest. Let it land before you decide anything.",
    catalyst: "Season check. Then pick one tile and move.",
    challenger: "If the season name bothers you, that's useful. Don't rebrand it.",
    bestFriend: "The season is just a name for now. We can work with now.",
    mother: "This season isn't a verdict. It's the weather. Dress for it.",
    roaster: "Cute season name. Still doesn't do the work for you.",
  },
  'dashboardSignal::default': {
    bestFriend: "This is what they reflected back. Hold it like a friend would — curious, not defensive.",
    mother: "The signal is a reading, not a sentence. We'll look together.",
    roaster: "Find the number you hate. That's where we start, not the one that flatters you.",
  },
  'dashboardSignal::snapshot': {
    mentor: "This is your signal at rest. Walk it again any time — or go verify it in the evidence room.",
    catalyst: "Snapshot. Walk it again or go get the receipts.",
    challenger: "Don't admire the dashboard. Go prove or disprove it in Evidence.",
    bestFriend: "Here's the picture at rest. We can walk it again whenever you want.",
    mother: "The signal keeps. Come back when you're ready to look closer.",
    roaster: "Pretty snapshot. Evidence is where you stop guessing.",
  },
  'dashboardSignal::threshold': {
    mentor: "The signal is what your team is reflecting back. Hold it lightly — patterns matter more than any one number.",
    catalyst: "Threshold. Look at the whole, then we'll walk trait by trait.",
    challenger: "Don't hunt a single number to fight. Watch the pattern.",
    bestFriend: "We're at the door of the signal. Patterns first, arguments later.",
    mother: "Come to the threshold. We'll take this in pieces so it stays human.",
    roaster: "Welcome to the mirror. Try not to litigate the first number you see.",
  },
  'dashboardSignal::traits': {
    mentor: "Three traits, one at a time — strongest ground first. The arrow walks you down; nothing is hidden, just paced.",
    catalyst: "One trait at a time. Strongest ground first. Keep walking.",
    challenger: "Don't skip to your least favorite. Walk the order.",
    bestFriend: "We'll do these one by one. I won't dump all three on you at once.",
    mother: "One trait, then the next. You don't have to swallow the year in one look.",
    roaster: "Three courses. Eat in order. Skipping to dessert is how you stay confused.",
  },
  'dashboardSignal::gap': {
    mentor: "Three gaps, one at a time. When your read and your team's diverge, neither is wrong — the distance itself is the finding.",
    catalyst: "Gaps next. Distance is the finding, not a verdict.",
    challenger: "If you and they disagree, that's the work. Don't pick a winner yet.",
    bestFriend: "The gaps aren't a fight. They're where a conversation would help.",
    mother: "When you and they see it differently, we'll treat the distance with care.",
    roaster: "The gap is not them being wrong. It's the space you refused to see.",
  },
  'dashboardSignal::checkin': {
    mentor: "However this is landing for you is the right answer. I just want to know where you are.",
    catalyst: "Check-in. Name the feeling. Then we pick a door.",
    challenger: "Don't perform calm. Where did this actually land?",
    bestFriend: "Hey — how is this sitting? There's no correct feeling.",
    mother: "How is your body taking this? We'll go from there.",
    roaster: "Feelings check. If you say 'fine,' I'm going to wait.",
  },
  'dashboardSignal::close': {
    mentor: "A debrief should end in a door, not a number. Pick the one that matches where you are.",
    catalyst: "Pick a door. Evidence or sit with it — don't hover.",
    challenger: "Close means choose. Lingering on the chart is stalling.",
    bestFriend: "That's the walk. Next door is yours — I'd go see the receipts.",
    mother: "We've looked. Choose the next room when you're ready. Evidence is waiting.",
    roaster: "End in a door. Numbers aren't a lifestyle.",
  },
  'dashboardEvidence::default': {
    bestFriend: "Receipts now. Nothing here is a speech — just what they actually marked.",
    mother: "We'll look at the sourced lines. No summarizing on your behalf.",
    roaster: "If the evidence surprises you, you were guessing. Good. Guess less.",
  },
  'dashboardEvidence::snapshot': {
    mentor: "The receipts keep. Come back any time a claim needs checking — or walk the room again.",
    catalyst: "Evidence at rest. Replay or go make a practice.",
    challenger: "Don't leave a claim unchecked. The room is still here.",
    bestFriend: "We can come back anytime. The receipts don't expire.",
    mother: "This room keeps. Return when a number needs a witness.",
    roaster: "Snapshot of receipts. Still not a vibe. Check them.",
  },
  'dashboardEvidence::ev-intro': {
    mentor: "Evidence is sourced, not stylized. Take your time in here — nothing is summarized on your behalf.",
    catalyst: "Receipts. Read them. Then decide what to change.",
    challenger: "If you only wanted a story, you wouldn't be in this room.",
    bestFriend: "This is the evidence locker. Slow is okay.",
    mother: "We'll look at what was actually said. No varnish.",
    roaster: "Sourced, not stylized. Your narrative can wait outside.",
  },
  'dashboardEvidence::ev-floor': {
    mentor: "Three statements, ranked by need. If you only change one thing this cycle, the top of this list is where it counts.",
    catalyst: "The floor. Top of the list is the one-change bet.",
    challenger: "Don't pick a prettier statement lower down. The ranking already told you.",
    bestFriend: "If you only fix one thing, it's the top line. I'll remind you later.",
    mother: "These are ranked by need. Honor the order even if it's uncomfortable.",
    roaster: "The floor isn't a suggestion. It's the pile you keep tripping on.",
  },
  'dashboardEvidence::ev-gaps': {
    mentor: "A gap isn't an accusation. It's a precise map of where a conversation would teach you the most.",
    catalyst: "Gaps. Conversation map, not a courtroom.",
    challenger: "Don't explain the gap away. Go ask someone living it.",
    bestFriend: "Gaps are just 'we see this differently.' That's a talk, not a trial.",
    mother: "Distance between you and them is information. We'll treat it gently and specifically.",
    roaster: "A gap isn't they 'don't get you.' It's you not getting how you land.",
  },
  'dashboardEvidence::ev-trait': {
    mentor: "One trait exhibit at a time. Read the receipts for this trait before you invent a story about it.",
    catalyst: "This trait's receipts. Read, then interpret.",
    challenger: "Don't write the myth. Read the five lines.",
    bestFriend: "Just this trait. We'll get to the others. Look at what they marked.",
    mother: "One exhibit. Stay with these statements until they feel specific.",
    roaster: "Trait exhibit. Your story about this trait is not evidence.",
  },
  'dashboardEvidence::ev-close': {
    mentor: "Verified ground. Now we build on it — an action plan for every trait, starting where the signal points.",
    catalyst: "Verified. Practice is next. Keep it small enough to keep.",
    challenger: "You saw it. Now pick a behavior they could notice. Not a slogan.",
    bestFriend: "We've checked the receipts. Next is one practice they can actually feel.",
    mother: "The ground is checked. We'll make a plan that fits a real week.",
    roaster: "Receipts closed. If your plan is 'be more strategic,' I'm sending you back.",
  },
  'dashboardPractice::default': {
    bestFriend: "Not a new you. One visible behavior per trait — small enough you'd actually do it.",
    mother: "Practice is how they feel the year. Keep it human-sized.",
    roaster: "A plan you won't do is worse than no plan. Shrink it until it's embarrassing.",
  },
  'dashboardPractice::snapshot': {
    mentor: "The bearing is set. These promises hold until the next check-in reads the signal again.",
    catalyst: "Bearing set. Keep them small enough to keep.",
    challenger: "Promises are public to you. Don't quietly drop them.",
    bestFriend: "These are the promises. We'll see them again at the next reading.",
    mother: "The plans stay until the next check-in. Tend them like something living.",
    roaster: "Snapshot of promises. Still have to do them. Weird how that works.",
  },
  'dashboardPractice::pr-intro': {
    mentor: "You are not starting over. You are carrying the signal into practice now — a plan for every trait, one visible behavior at a time.",
    catalyst: "Signal in, practice out. One visible behavior per trait.",
    challenger: "If the plan isn't visible to them, it isn't a plan.",
    bestFriend: "We're turning the reading into something they could notice by Friday.",
    mother: "Practice is how care becomes visible. We'll keep it small.",
    roaster: "Don't start over. Start doing the thing the signal already named.",
  },
  'dashboardPractice::pr-edge': {
    mentor: "Start where the signal points. This trait is asking for a different approach, not more effort.",
    catalyst: "Edge trait. Change the aim, not the hours.",
    challenger: "More grind here is how you stay stuck. Change the move.",
    bestFriend: "This is the tender one. Different approach — I'll sit with you while you pick it.",
    mother: "The edge needs a gentler, truer move — not more of the same trying.",
    roaster: "The edge. If your plan is 'try harder,' that's the problem in a costume.",
  },
  'dashboardPractice::pr-lifting': {
    mentor: "This is already a gift — the plan is about keeping it deliberate so it grows instead of coasting.",
    catalyst: "Gift trait. Put a little intention on it so it doesn't coast.",
    challenger: "Gifts die of neglect. Don't coast this one.",
    bestFriend: "This one's already working. Let's not sleep on it.",
    mother: "What's lifting you can still use tending. Name how you'll keep it kind and awake.",
    roaster: "Natural gift. Cool. Coasting is how gifts become folklore.",
  },
  'dashboardPractice::pr-strength': {
    mentor: "This is strong because you work at it. Protect the strength — and you — from quiet erosion.",
    catalyst: "Held strength. Protect it from burnout dressed as virtue.",
    challenger: "High effort, high result is expensive. Don't martyr it.",
    bestFriend: "You're good here because you work it. Let's not let it eat you.",
    mother: "Strength that costs you still needs rest and a plan, not just praise.",
    roaster: "You earned this one. Don't confuse exhaustion with excellence.",
  },
  'dashboardPractice::pr-commit': {
    mentor: "Promises, said out loud. Keep them small enough that you actually do them.",
    catalyst: "Say them. Calendar them. If they don't fit, shrink them.",
    challenger: "If you can't name when you'll do it, you didn't commit.",
    bestFriend: "Say the promises like you'd say them to me. Then actually do them.",
    mother: "Commitments should fit a life. If they don't, we rewrite before we pretend.",
    roaster: "Commitment theater is free. Doing it isn't. Pick the second.",
  },
  'dashboardJourney::default': {
    bestFriend: "The whole trail. You've already come a way — then we look at the next open station.",
    mother: "See how far you've walked before you stare at what's left.",
    roaster: "Don't camp on completed stations. Open the next door.",
  },
  'dashboardJourney::station-focus': {
    mentor: "This station has a job. If it's open, that's the work. If it's done, don't relive it.",
    catalyst: "Focused a station. If it's next, go. If it's done, keep walking.",
    challenger: "Nostalgia isn't progress. What's the next open door?",
    bestFriend: "This stop on the trail — are we here to do something, or just look?",
    mother: "This chapter has its own season. Meet it where it is.",
    roaster: "Nice station. Is it your job today or are you sightseeing?",
  },
  'dashboardGate::default': {
    mentor: "One step at a time. Finish the prior station before you force this door open.",
    catalyst: "Gated on purpose. Finish the room before this one.",
    challenger: "You don't get to skip the reading. Go back and do the last room.",
    bestFriend: "This door's locked because the last one still needs you. I'll walk you back.",
    mother: "Not yet. The earlier room is still teaching. We'll come here after.",
    roaster: "Locked. That's not a bug. Go finish the thing you skipped.",
  },
};
